[package]
name = "vogls-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "vogls"
path = "src/main.rs"
doc = false

[dependencies]
vogls = { workspace = true, features = ["unstable", "profile", "stdworld"] }
clap.workspace = true

[lints]
workspace = true

[features]
default = ["native"]
tailcall = ["vogls/tailcall"]
native = ["vogls/native"]
