[package]
name = "vogls-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "vogls"
path = "src/main.rs"
doc = false

[dependencies]
vogls = { workspace = true, features = ["unstable", "native"] }
clap.workspace = true

[lints]
workspace = true

[features]
tailcall = ["vogls/tailcall"]
