[workspace]
members = [
    "vogls",
    "vogls-test",
    "vogls-ir",
    "vogls-ir-properties",
    "vogls-bits",
    "vogls-sim",
    # "vogls-sdf",
    "vogls-verilog",
    "vogls-frontend",
	# "vogls-bytecode",
    "vogls-utils",
	"vogls-python",
	"vogls-codegen",
	"vogls-codegen-c",
    "vogls-runtime",
    "vogls-vcd",
	"vogls-fuse-signals",
]
resolver = "3"

[workspace.package]
version = "0.0.1"
edition = "2024"

[workspace.dependencies]
slotmap = "1"
bytemuck = "1"
proptest = "1"
hashbrown = "0.16"
foldhash = "0.2.0"
rand = "0.10"
clap = { version = "4.5", features = ["derive"] }
bumpalo = "3.20"
tempfile = "3.27.0"

vogls.path = "vogls"
vogls-frontend.path = "vogls-frontend"
vogls-sim.path = "vogls-sim"
vogls-ir.path = "vogls-ir"
vogls-ir-properties.path = "vogls-ir-properties"
vogls-fuse-signals.path = "vogls-fuse-signals"
vogls-bits.path = "vogls-bits"
vogls-verilog.path = "vogls-verilog"
vogls-utils.path = "vogls-utils"
vogls-codegen.path = "vogls-codegen"
vogls-codegen-c.path = "vogls-codegen-c"
vogls-runtime.path = "vogls-runtime"
vogls-vcd.path = "vogls-vcd"

[profile.debug-release]
inherits = "release"
debug = true

[workspace.lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(vm_profile)'] }
