[workspace]
members = [
    "crates/*",
    
    "tools/pipeline-explorer",
    "tools/trva/trva",
    "tools/trva/cli",
    "tools/trva/snapshot-tests",
]
resolver = "3"

[workspace.package]
version = "0.0.1"
edition = "2024"

[workspace.dependencies]
slotmap = "1"
bytemuck = "1"
libc = "0.2"
proptest = "1"
hashbrown = "0.17"
foldhash = "0.2.0"
rayon = "1.12.0"
rand = "0.10"
clap = { version = "4.5", features = ["derive"] }
bumpalo = "3.20"
pyo3 = { version = "0.28.1", features = ["abi3-py311"] }

cranelift-codegen = { version = "0.134", default-features = false }
cranelift-frontend = { version = "0.134", default-features = false }
cranelift-module = { version = "0.134", default-features = false }
cranelift-jit = { version = "0.134", default-features = false }
cranelift-native = { version = "0.134", default-features = false }

vogls = { path = "crates/vogls", default-features = false }
vogls-frontend.path = "crates/vogls-frontend"
vogls-bytecode.path = "crates/vogls-bytecode"
vogls-ir.path = "crates/vogls-ir"
vogls-fuse-signals.path = "crates/vogls-fuse-signals"
vogls-bits.path = "crates/vogls-bits"
vogls-verilog.path = "crates/vogls-verilog"
vogls-utils.path = "crates/vogls-utils"
vogls-codegen.path = "crates/vogls-codegen"
vogls-codegen-clif.path = "crates/vogls-codegen-clif"
vogls-runtime.path = "crates/vogls-runtime"
vogls-vcd.path = "crates/vogls-vcd"
vogls-sdf.path = "crates/vogls-sdf"
vogls-trace.path = "crates/vogls-trace"
vogls-plan.path = "crates/vogls-plan"
vogls-world = { path = "crates/vogls-world", default-features = false }

pipeline-explorer.path = "tools/pipeline-explorer"
trva.path = "tools/trva/trva"

[profile.debug-release]
inherits = "release"
debug = true

[profile.fast-dev]
inherits = "dev"
opt-level = 3

[workspace.lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(vm_profile)'] }

[workspace.lints.clippy]
result_unit_err = "allow"
collapsible_if = "allow"
too_many_arguments = "allow"
needless_range_loop = "allow"
type_complexity = "allow"
