[package]
name = "vogls-python"
version.workspace = true
edition.workspace = true

[lib]
name = "vogls"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.28.1"
vogls = { workspace = true, features = ["random"] }
vogls-trace.workspace = true
vogls-plan.workspace = true
hashbrown.workspace = true

[lints]
workspace = true
