[package]
name = "vogls-test"
version.workspace = true
edition.workspace = true

[dependencies]
slotmap.workspace = true
clap.workspace = true
rayon.workspace = true
regex = "1.13.1"
vogls = { workspace = true, features = ["native"] }
vogls-ir.workspace = true
vogls-bytecode.workspace = true
vogls-verilog.workspace = true

[lints]
workspace = true
