[package]
name = "vogls-test"
version.workspace = true
edition.workspace = true

[dependencies]
slotmap.workspace = true
clap.workspace = true
rayon.workspace = true
vogls = { workspace = true, features = ["native"] }
vogls-ir.workspace = true
vogls-sim.workspace = true
vogls-verilog.workspace = true
