[package]
name = "vogls-python"
version.workspace = true
edition.workspace = true

[lib]
name = "vogls"
crate-type = ["cdylib"]

[dependencies]
pyo3.workspace = true
vogls = { workspace = true, features = ["random", "unstable", "native"] }
vogls-trace.workspace = true
vogls-plan = { workspace = true, features = ["python"] }
hashbrown.workspace = true

[lints]
workspace = true
