[package]
name = "vogls-bytecode"
version.workspace = true
edition.workspace = true

[dependencies]
slotmap.workspace = true
bytemuck.workspace = true
vogls-ir.workspace = true
vogls-bits.workspace = true
vogls-utils.workspace = true
vogls-codegen.workspace = true
vogls-runtime.workspace = true
vogls-vcd.workspace = true

[lints]
workspace = true

[features]
tailcall = []
