[package]
name = "vogls"
version.workspace = true
edition.workspace = true

[dependencies]
clap.workspace = true
slotmap.workspace = true
vogls-ir.workspace = true
vogls-sim.workspace = true
vogls-trace.workspace = true
vogls-verilog.workspace = true
vogls-frontend.workspace = true
vogls-utils.workspace = true
vogls-bits.workspace = true
vogls-codegen.workspace = true
vogls-codegen-c.workspace = true
vogls-runtime.workspace = true

[features]
random = ["vogls-bits/random"]
