wasm:
    cargo build --lib --target=wasm32-unknown-unknown
    wasm-bindgen ../../target/wasm32-unknown-unknown/debug/pipeline_explorer.wasm --out-dir webapp/src/wasm --target web

wasm-release:
    cargo build --lib --release --target=wasm32-unknown-unknown
    wasm-bindgen ../../target/wasm32-unknown-unknown/release/pipeline_explorer.wasm --out-dir webapp/src/wasm --target web

webapp-deps:
    cd webapp && npm install

build-site: wasm-release webapp-deps
    cd webapp && npm run build