[package]
name = "vogls-trace"
version.workspace = true
edition.workspace = true

[dependencies]
vogls-runtime.workspace = true
vogls-codegen.workspace = true
vogls.workspace = true
vogls-bits.workspace = true
vogls-ir.workspace = true
vogls-utils.workspace = true
hashbrown.workspace = true

[lints]
workspace = true
